#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""
Employee Creative Ideation Module — P34

Enables employees to generate creative ideas and suggestions like in a real company.
Unlike P26 (reactive TODO scanning), P34 is proactive ideation based on experience.

Ideation Types:
- process_improvement: "I've done X task 5 times, we should automate it"
- bottleneck_observation: "Task type Y keeps failing, root cause is Z"
- capability_expansion: "I keep getting tasks needing Z, I should learn it"
- collaboration_proposal: "My work overlaps with [employee], we should sync"
- tool_suggestion: "A tool for X would save time"
- architecture_insight: "These modules are coupled, should refactor"
- strategic_observation: "Pattern in backlog suggests we need X"

Usage:
    # Run ideation for a specific employee
    python employee_ideation.py ideate --employee-id "senior-python-developer"

    # Run ideation cycle for all employees
    python employee_ideation.py cycle

    # Get ideation stats
    python employee_ideation.py stats

    # List recent ideas
    python employee_ideation.py list --days 7
"""

from __future__ import annotations

import hashlib
import json
import sys
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta, timezone
from enum import Enum
from pathlib import Path

# Lazy imports
work_allocator = None
company_resolver = None
goal_tracker = None
_escalation_module = None


def _ensure_imports():
    """Lazily import sibling modules."""
    global work_allocator, company_resolver, goal_tracker
    if work_allocator is not None:
        return

    try:
        from . import company_resolver as cr
        from . import goal_tracker as gt
        from . import work_allocator as wa

        work_allocator = wa
        company_resolver = cr
        goal_tracker = gt
    except ImportError:
        import company_resolver as cr  # type: ignore[no-redef]
        import goal_tracker as gt  # type: ignore[no-redef]
        import work_allocator as wa  # type: ignore[no-redef]

        work_allocator = wa
        company_resolver = cr
        goal_tracker = gt


def _ensure_escalation():
    """Lazily import escalation module for opt-in notifications."""
    global _escalation_module
    if _escalation_module is not None:
        return _escalation_module
    try:
        from . import escalation as esc

        _escalation_module = esc
    except ImportError:
        try:
            import escalation as esc  # type: ignore[no-redef]

            _escalation_module = esc
        except ImportError:
            _escalation_module = None
    return _escalation_module


def fire_pending_approvals_notification(count: int, idea_ids: list[str]) -> None:
    """Fire one notification via notifications.escalation machinery for pending ideas.

    Reads notifications.escalation from forge-config.json (same config key as
    escalation.py uses).  Both channels are off by default — this is a no-op
    unless explicitly enabled.  Any error is swallowed; it must never affect
    the queued ideas or the ideation result.
    """
    try:
        esc = _ensure_escalation()
        if esc is None:
            return

        notif_cfg = esc._get_opt_in_notifications_config()
        title = f"{count} idea(s) pending approval"

        osascript_cfg = notif_cfg.get("osascript", {})
        if osascript_cfg.get("enabled", False):
            esc._send_osascript_notification(
                task_id="ideation-batch",
                tier=1,
                reason="pending_approval",
                task_title=title,
            )

        webhook_cfg = notif_cfg.get("webhook", {})
        if webhook_cfg.get("enabled", False) and webhook_cfg.get("url"):
            payload: dict = {
                "event": "ideas_pending_approval",
                "count": count,
                "idea_ids": idea_ids[:10],
            }
            esc._send_webhook_notification(
                webhook_cfg["url"],
                payload,
                webhook_cfg.get("headers", {}),
            )
    except Exception:
        pass  # Never affect ideation handling


class IdeationType(Enum):
    """Types of creative ideas employees can generate."""

    PROCESS_IMPROVEMENT = "process_improvement"
    BOTTLENECK_OBSERVATION = "bottleneck_observation"
    CAPABILITY_EXPANSION = "capability_expansion"
    COLLABORATION_PROPOSAL = "collaboration_proposal"
    TOOL_SUGGESTION = "tool_suggestion"
    ARCHITECTURE_INSIGHT = "architecture_insight"
    STRATEGIC_OBSERVATION = "strategic_observation"


@dataclass
class Idea:
    """A creative idea generated by an employee."""

    idea_id: str
    employee_id: str
    idea_type: IdeationType
    title: str
    description: str
    rationale: str  # Why the employee thinks this is valuable
    evidence: list[dict]  # Supporting data from their experience
    estimated_value: float  # 0.0 to 1.0
    estimated_effort: str  # trivial, standard, complex
    created_at: str
    status: str = "proposed"  # proposed, approved, rejected, implemented
    related_tasks: list[str] = field(default_factory=list)
    related_employees: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        d = asdict(self)
        d["idea_type"] = self.idea_type.value
        return d

    @classmethod
    def from_dict(cls, data: dict) -> "Idea":
        """Create from dictionary."""
        data = data.copy()
        if isinstance(data.get("idea_type"), str):
            data["idea_type"] = IdeationType(data["idea_type"])
        return cls(**data)


@dataclass
class ProductContext:
    """Product context extracted from .company/vision.md goals."""

    goals: list  # list[GoalDefinition]
    active_goal_names: list[str]
    active_metrics: list[str]
    is_valid: bool  # False when vision.md is absent or has no parseable goals


def get_company_dir() -> Path:
    """Get the company directory path."""
    _ensure_imports()
    return company_resolver.get_company_dir()


def load_product_context() -> ProductContext:
    """Load product context from .company/vision.md.

    Returns ProductContext with is_valid=False if vision.md is absent or has
    no parseable goal table rows, so callers can gate idea generation on it.
    """
    _ensure_imports()
    company_dir = get_company_dir()
    vision_path = company_dir / "vision.md"

    if not vision_path.exists():
        return ProductContext(
            goals=[], active_goal_names=[], active_metrics=[], is_valid=False
        )

    try:
        goals = goal_tracker.parse_goals_from_vision(vision_path, period="active")
        # parse_goals_from_vision returns DEFAULT_GOALS (not empty) when
        # the file has no parseable table rows — detect that via identity check.
        if goals is goal_tracker.DEFAULT_GOALS:
            goals = goal_tracker.parse_goals_from_vision(vision_path, period="all")
        if not goals or goals is goal_tracker.DEFAULT_GOALS:
            print(
                f"warning: {vision_path} has no parseable goal table; ideation disabled."
                " Add goals under a period header, e.g.:"
                " ### Period: Q1 2026 [status: active]"
                " | G1: Goal Name | Description | Success metric | owner |",
                file=sys.stderr,
            )
            return ProductContext(
                goals=[], active_goal_names=[], active_metrics=[], is_valid=False
            )
        return ProductContext(
            goals=goals,
            active_goal_names=[g.name for g in goals],
            active_metrics=[g.success_metric for g in goals if g.success_metric],
            is_valid=True,
        )
    except Exception:
        return ProductContext(
            goals=[], active_goal_names=[], active_metrics=[], is_valid=False
        )


def get_ideas_path() -> Path:
    """Get path to ideas storage file."""
    return get_company_dir() / "employee_ideas.json"


def load_ideas() -> dict:
    """Load ideas from storage."""
    path = get_ideas_path()
    if not path.exists():
        return {
            "ideas": [],
            "metadata": {"created_at": datetime.now(timezone.utc).isoformat()},
        }
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {
            "ideas": [],
            "metadata": {"created_at": datetime.now(timezone.utc).isoformat()},
        }


def save_ideas(data: dict) -> None:
    """Save ideas to storage with atomic write."""
    import os
    import tempfile

    path = get_ideas_path()
    data["metadata"]["last_modified"] = datetime.now(timezone.utc).isoformat()

    # Atomic write
    dir_path = path.parent
    dir_path.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=dir_path, suffix=".json")
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp_path, path)
    except Exception:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise


def is_duplicate_idea(title: str, idea_type: str) -> tuple[bool, str | None]:
    """
    Check if an idea is a duplicate of an existing pending proposal or queued task.

    Returns (is_duplicate, reason) tuple.
    """
    # Normalize title for comparison
    title_lower = title.lower()

    # Extract the key pattern (e.g., "documentation" from "Automate repeated 'documentation' tasks")
    pattern_key = None
    if "repeated" in title_lower and "'" in title:
        # Extract quoted pattern
        start = title.find("'")
        end = title.find("'", start + 1)
        if start != -1 and end != -1:
            pattern_key = title[start + 1 : end].lower()

    # Check pending proposals in initiative engine
    try:
        pending_path = get_company_dir() / "state/pending_approvals.json"
        if pending_path.exists():
            with open(pending_path) as f:
                pending_data = json.load(f)

            for prop in pending_data.get("pending", []):
                prop_title = prop.get("title", "").lower()
                # Check for similar titles
                if pattern_key and pattern_key in prop_title:
                    return True, f"Similar pending proposal: {prop.get('proposal_id')}"
                if title_lower == prop_title:
                    return True, f"Exact match pending: {prop.get('proposal_id')}"
    except (json.JSONDecodeError, OSError):
        pass

    # Check pending tasks in work queue
    try:
        queue_path = get_company_dir() / "state/work_queue.json"
        if queue_path.exists():
            with open(queue_path) as f:
                queue_data = json.load(f)

            for task in queue_data.get("tasks", []):
                if task.get("status") not in ("pending", "active"):
                    continue
                task_title = task.get("title", "").lower()
                # Check for similar titles
                if pattern_key and pattern_key in task_title:
                    return True, f"Similar pending task: {task.get('task_id')}"
    except (json.JSONDecodeError, OSError):
        pass

    # Check existing ideas in employee_ideas.json
    try:
        ideas_path = get_company_dir() / "employee_ideas.json"
        if ideas_path.exists():
            with open(ideas_path) as f:
                ideas_data = json.load(f)

            for idea in ideas_data.get("ideas", []):
                idea_title = idea.get("title", "").lower()
                if pattern_key and pattern_key in idea_title:
                    return True, f"Similar existing idea: {idea.get('idea_id')}"
                if title_lower == idea_title:
                    return True, f"Exact match idea: {idea.get('idea_id')}"
    except (json.JSONDecodeError, OSError):
        pass

    return False, None


def generate_idea_id(employee_id: str, idea_type: str) -> str:
    """Generate unique idea ID."""
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    hash_input = f"{employee_id}-{idea_type}-{timestamp}"
    short_hash = hashlib.sha256(hash_input.encode()).hexdigest()[:6]
    return f"idea-{timestamp}-{short_hash}"


# Domain-specific ideation prompts for under-represented employees.
# Maps capability keywords to focused idea themes that play to each employee's strengths.
DOMAIN_IDEA_THEMES: dict[str, list[dict[str, str]]] = {
    "customer-support": [
        {
            "type": "process_improvement",
            "theme": "onboarding friction points",
            "prompt": "What steps in the customer onboarding flow are confusing or could be streamlined?",
        },
        {
            "type": "tool_suggestion",
            "theme": "support tooling",
            "prompt": "What internal tools would help resolve support tickets faster?",
        },
    ],
    "testing": [
        {
            "type": "process_improvement",
            "theme": "test coverage gaps",
            "prompt": "Which modules lack test coverage and would benefit most from new tests?",
        },
        {
            "type": "tool_suggestion",
            "theme": "test automation",
            "prompt": "What repetitive testing steps could be automated?",
        },
    ],
    "quality-assurance": [
        {
            "type": "process_improvement",
            "theme": "regression prevention",
            "prompt": "What patterns in recent bugs suggest areas needing better quality gates?",
        },
        {
            "type": "bottleneck_observation",
            "theme": "release quality",
            "prompt": "Where do quality issues most often slip through to production?",
        },
    ],
    "lead-qualification": [
        {
            "type": "strategic_observation",
            "theme": "sales pipeline",
            "prompt": "What signals from trial users indicate high conversion potential?",
        },
        {
            "type": "process_improvement",
            "theme": "demo flow",
            "prompt": "How could the demo or trial experience be improved to increase conversions?",
        },
    ],
    "metrics-definition": [
        {
            "type": "strategic_observation",
            "theme": "analytics gaps",
            "prompt": "What key metrics are we not tracking that would improve decision-making?",
        },
        {
            "type": "tool_suggestion",
            "theme": "dashboards",
            "prompt": "What dashboards or reports would help the team understand performance better?",
        },
    ],
    "financial-planning": [
        {
            "type": "strategic_observation",
            "theme": "unit economics",
            "prompt": "What cost drivers should we track to ensure sustainable growth?",
        },
        {
            "type": "process_improvement",
            "theme": "budget efficiency",
            "prompt": "Where are we spending resources that could be better allocated?",
        },
    ],
    "saas-marketing": [
        {
            "type": "strategic_observation",
            "theme": "market positioning",
            "prompt": "What messaging or positioning changes would better reach our target audience?",
        },
        {
            "type": "process_improvement",
            "theme": "content pipeline",
            "prompt": "How could our content creation process be more efficient?",
        },
    ],
    "web-design": [
        {
            "type": "process_improvement",
            "theme": "UX improvements",
            "prompt": "What website UX patterns could improve visitor engagement?",
        },
        {
            "type": "tool_suggestion",
            "theme": "design system",
            "prompt": "What design system components would speed up future page creation?",
        },
    ],
    "user-research": [
        {
            "type": "process_improvement",
            "theme": "feedback loops",
            "prompt": "How could we better capture and act on user feedback?",
        },
        {
            "type": "strategic_observation",
            "theme": "user needs",
            "prompt": "What unmet user needs have you observed that we should address?",
        },
    ],
    "python": [
        {
            "type": "process_improvement",
            "theme": "developer experience",
            "prompt": "What development workflow friction points slow down implementation?",
        },
        {
            "type": "tool_suggestion",
            "theme": "dev tooling",
            "prompt": "What tools or scripts would improve developer productivity?",
        },
    ],
    "vision": [
        {
            "type": "strategic_observation",
            "theme": "company direction",
            "prompt": "What strategic opportunities should we prioritize for growth?",
        },
        {
            "type": "collaboration_proposal",
            "theme": "cross-team alignment",
            "prompt": "Where do teams need better coordination to achieve company goals?",
        },
    ],
    "technical-vision": [
        {
            "type": "architecture_insight",
            "theme": "technical direction",
            "prompt": "What architectural improvements would most benefit long-term maintainability?",
        },
        {
            "type": "strategic_observation",
            "theme": "tech strategy",
            "prompt": "What emerging technologies or patterns should we evaluate?",
        },
    ],
    "security-audit": [
        {
            "type": "process_improvement",
            "theme": "security review process",
            "prompt": "What security review steps should be automated or standardized?",
        },
        {
            "type": "bottleneck_observation",
            "theme": "vulnerability patterns",
            "prompt": "What recurring vulnerability patterns have you observed that need systemic fixes?",
        },
    ],
    "hook-system": [
        {
            "type": "architecture_insight",
            "theme": "hook infrastructure",
            "prompt": "What hook system improvements would increase reliability and maintainability?",
        },
        {
            "type": "tool_suggestion",
            "theme": "hook tooling",
            "prompt": "What tools or utilities would make hook development and debugging easier?",
        },
    ],
    "architecture": [
        {
            "type": "architecture_insight",
            "theme": "system design",
            "prompt": "What structural changes would reduce coupling and improve modularity?",
        },
        {
            "type": "strategic_observation",
            "theme": "design patterns",
            "prompt": "What design patterns from other systems could improve our architecture?",
        },
    ],
    "design-decisions": [
        {
            "type": "process_improvement",
            "theme": "decision documentation",
            "prompt": "How can we better document and track architectural decisions and their rationale?",
        },
        {
            "type": "collaboration_proposal",
            "theme": "design review",
            "prompt": "How should design reviews be structured to catch issues earlier?",
        },
    ],
    "go-to-market": [
        {
            "type": "strategic_observation",
            "theme": "market positioning",
            "prompt": "What market positioning opportunities are we missing based on current trends?",
        },
        {
            "type": "capability_expansion",
            "theme": "GTM channels",
            "prompt": "What go-to-market channels should we explore to reach new user segments?",
        },
    ],
    "content-strategy": [
        {
            "type": "strategic_observation",
            "theme": "content planning",
            "prompt": "What content themes would best demonstrate our value proposition?",
        },
        {
            "type": "process_improvement",
            "theme": "content pipeline",
            "prompt": "How can we streamline the content creation and publishing workflow?",
        },
    ],
    "backend": [
        {
            "type": "architecture_insight",
            "theme": "backend reliability",
            "prompt": "What backend infrastructure changes would most improve system reliability?",
        },
        {
            "type": "bottleneck_observation",
            "theme": "backend performance",
            "prompt": "What backend performance bottlenecks have you observed that need addressing?",
        },
    ],
    "html": [
        {
            "type": "process_improvement",
            "theme": "web structure",
            "prompt": "What improvements to HTML structure would enhance accessibility and SEO?",
        },
        {
            "type": "tool_suggestion",
            "theme": "frontend tooling",
            "prompt": "What frontend tools or templates would speed up web page development?",
        },
    ],
    "css": [
        {
            "type": "architecture_insight",
            "theme": "design system",
            "prompt": "What design system improvements would ensure visual consistency across pages?",
        },
        {
            "type": "process_improvement",
            "theme": "styling workflow",
            "prompt": "How can we reduce CSS duplication and improve the styling workflow?",
        },
    ],
    "packaging": [
        {
            "type": "process_improvement",
            "theme": "distribution workflow",
            "prompt": "What packaging and distribution steps should be automated for faster releases?",
        },
        {
            "type": "bottleneck_observation",
            "theme": "packaging issues",
            "prompt": "What packaging issues have caused the most friction for users or developers?",
        },
    ],
    "installation": [
        {
            "type": "process_improvement",
            "theme": "install experience",
            "prompt": "What installation experience improvements would reduce user setup friction?",
        },
        {
            "type": "tool_suggestion",
            "theme": "install tooling",
            "prompt": "What tools or scripts would make installation testing and validation easier?",
        },
    ],
}


def _get_domain_themes_for_employee(employee: dict) -> list[dict[str, str]]:
    """Get domain-specific idea themes matching employee capabilities."""
    capabilities = employee.get("capabilities", [])
    themes: list[dict[str, str]] = []
    seen_themes: set[str] = set()
    for cap in capabilities:
        for domain_themes in DOMAIN_IDEA_THEMES.get(cap, []):
            theme_key = domain_themes["theme"]
            if theme_key not in seen_themes:
                themes.append(domain_themes)
                seen_themes.add(theme_key)
    return themes


def generate_zero_activity_ideas(
    employee_id: str, employee: dict, product_ctx: ProductContext
) -> list[Idea]:
    """
    Generate product-grounded ideas for employees with low/zero task activity.

    Requires valid product context (vision.md with parsed goals). Returns an
    empty list when product_ctx.is_valid is False so that idle employees don't
    invent generic self-improvement work unrelated to the actual product.
    """
    if not product_ctx.is_valid:
        return []

    emp_name = employee.get("name", employee_id)
    department = employee.get("department", "unknown")
    capabilities = employee.get("capabilities", [])
    cap_str = ", ".join(capabilities[:3]) if capabilities else "general skills"

    ideas: list[Idea] = []
    for goal in product_ctx.goals[:3]:  # Cap at 3 ideas
        ideas.append(
            Idea(
                idea_id=generate_idea_id(employee_id, f"vision-{goal.id}"),
                employee_id=employee_id,
                idea_type=IdeationType.STRATEGIC_OBSERVATION,
                title=f"[{department}] Advance {goal.name}: {goal.description}",
                description=(
                    f"As {emp_name} in {department}, I can contribute to the "
                    f"'{goal.name}' goal. Target: {goal.success_metric}. "
                    f"I will apply {cap_str} to help achieve this."
                ),
                rationale=(
                    f"Product goal {goal.id} ({goal.name}) is active. "
                    f"My capabilities can directly support: {goal.description}."
                ),
                evidence=[
                    {
                        "goal_id": goal.id,
                        "goal_name": goal.name,
                        "success_metric": goal.success_metric,
                    }
                ],
                estimated_value=0.6,
                estimated_effort="standard",
                created_at=datetime.now(timezone.utc).isoformat(),
                tags=[department, goal.id.lower(), "product-vision"],
            )
        )

    return ideas


def _get_covered_goal_ids(goal_ids: set[str]) -> set[str]:
    """Return lowercase goal IDs that already have open ideas or active tasks.

    A goal is "covered" when further ideation for it would produce a duplicate:
    - An idea with status "proposed" or "pending_approval" referencing that goal, OR
    - An active/pending task in the work queue tagged with that goal ID.
    """
    goal_ids_lower = {g.lower() for g in goal_ids}
    covered: set[str] = set()

    try:
        ideas_path = get_company_dir() / "employee_ideas.json"
        if ideas_path.exists():
            with open(ideas_path) as f:
                ideas_data = json.load(f)
            open_statuses = {"proposed", "pending_approval"}
            for idea in ideas_data.get("ideas", []):
                if idea.get("status") not in open_statuses:
                    continue
                if "goal-decomposition" not in idea.get("tags", []):
                    continue
                for ev in idea.get("evidence", []):
                    gid = ev.get("goal_id", "").lower()
                    if gid in goal_ids_lower:
                        covered.add(gid)
    except (json.JSONDecodeError, OSError):
        pass

    try:
        queue_path = get_company_dir() / "state/work_queue.json"
        if queue_path.exists():
            with open(queue_path) as f:
                queue_data = json.load(f)
            active_statuses = {"pending", "active"}
            for task in queue_data.get("tasks", []):
                if task.get("status") not in active_statuses:
                    continue
                for tag in task.get("tags", []):
                    if tag.lower() in goal_ids_lower:
                        covered.add(tag.lower())
    except (json.JSONDecodeError, OSError):
        pass

    return covered


def generate_goal_decomposition_ideas(
    employee_id: str,
    employee: dict,
    product_ctx: ProductContext,
    max_ideas: int = 3,
) -> list[Idea]:
    """Generate concrete next-step task ideas for each active product goal.

    Rotates across ALL goals to ensure full coverage across ideation cycles.
    Goals already covered by an open idea or active task are skipped (one open
    idea per goal cap). Uncovered goals are proposed first; goals whose owner
    matches this employee are preferred within each coverage band.

    Returns empty list when product_ctx.is_valid is False (safe default:
    no parseable goals → no ideas).
    """
    if not product_ctx.is_valid:
        return []

    emp_name = employee.get("name", employee_id)
    department = employee.get("department", "unknown")
    capabilities = employee.get("capabilities", [])
    cap_str = ", ".join(capabilities[:3]) if capabilities else "general skills"

    # Exclude goals already shipped/completed.
    active_goals = [g for g in product_ctx.goals if g.period_status != "complete"]

    # Exclude goals already verified post-merge via metric check.
    try:
        _ensure_imports()
        _ver_state = goal_tracker.load_goal_verification_state(get_company_dir())
        _verified_ids = {
            gid for gid, rec in _ver_state.items() if rec.get("status") == "verified"
        }
        active_goals = [g for g in active_goals if g.id not in _verified_ids]
    except Exception:
        pass  # Verification state unavailable — proceed without filtering

    all_goal_ids = {g.id for g in active_goals}
    covered_ids = _get_covered_goal_ids(all_goal_ids)

    def _owner_score(goal) -> int:
        if goal.owner == employee_id:
            return 2
        if goal.owner in capabilities:
            return 1
        return 0

    # Sort: uncovered first (0 < 1), then owner affinity descending, then stable index.
    sorted_goals = [
        goal
        for _, goal in sorted(
            enumerate(active_goals),
            key=lambda item: (
                int(item[1].id.lower() in covered_ids),
                -_owner_score(item[1]),
                item[0],
            ),
        )
    ]

    ideas: list[Idea] = []
    for goal in sorted_goals:
        if len(ideas) >= max_ideas:
            break
        # One open idea per goal: uncovered goals are sorted first, so the first
        # covered goal encountered means all remaining are also covered.
        if goal.id.lower() in covered_ids:
            break
        ideas.append(
            Idea(
                idea_id=generate_idea_id(employee_id, f"goal-{goal.id}"),
                employee_id=employee_id,
                idea_type=IdeationType.STRATEGIC_OBSERVATION,
                title=f"[{goal.id}] {goal.name}: advance toward {goal.success_metric}",
                description=(
                    f"Goal {goal.id} ({goal.name}) is active. "
                    f"Description: {goal.description}. "
                    f"Target: {goal.success_metric}. "
                    f"As {emp_name} ({department}, {cap_str}), "
                    f"the next concrete task is to contribute directly to this goal."
                ),
                rationale=(
                    f"Active goal {goal.id} ({goal.name}) requires: {goal.description}. "
                    f"Capabilities ({cap_str}) can directly advance this goal."
                ),
                evidence=[
                    {
                        "goal_id": goal.id,
                        "goal_name": goal.name,
                        "success_metric": goal.success_metric,
                        "description": goal.description,
                    }
                ],
                estimated_value=0.7,
                estimated_effort="standard",
                created_at=datetime.now(timezone.utc).isoformat(),
                tags=[department, goal.id.lower(), "goal-decomposition"],
            )
        )

    return ideas


def _normalize_employee_entry(entry) -> dict | None:
    """Normalize an org.json employees[] entry to a dict record.

    Thin module-local alias for the canonical
    company_resolver.normalize_employee_entry. A fresh /company-bootstrap run
    can write "employees" as bare ID strings instead of full records (the
    LLM-driven bootstrap skill can deviate from calling batch_hire.py). The
    single source of truth for that coercion now lives in company_resolver so
    all ~34 org consumers share one implementation (ProjectK root-cause fix).
    """
    _ensure_imports()  # guarantees company_resolver even if get_company_dir patched
    return company_resolver.normalize_employee_entry(entry, get_company_dir())


def load_org() -> dict:
    """Load organization data with employees normalized to dict records."""
    _ensure_imports()  # guarantees company_resolver even if get_company_dir patched
    company_dir = get_company_dir()  # module wrapper (patchable in tests)
    org_path = company_dir / "org.json"
    if not org_path.exists():
        return {"employees": []}
    try:
        with open(org_path) as f:
            org = json.load(f)
    except (json.JSONDecodeError, OSError):
        return {"employees": []}
    return company_resolver.normalize_org_employees(org, company_dir)


def get_employee(employee_id: str) -> dict | None:
    """Get employee data by ID."""
    org = load_org()
    for emp in org.get("employees", []):
        if emp.get("id") == employee_id:
            return emp
    return None


def load_learning_outcomes() -> list[dict]:
    """Load learning outcomes data."""
    path = get_company_dir() / "state/learning_outcomes.json"
    if not path.exists():
        return []
    try:
        with open(path) as f:
            data = json.load(f)
            return data.get("outcomes", [])
    except (json.JSONDecodeError, OSError):
        return []


def load_efficiency_data() -> dict:
    """Load efficiency tracking data."""
    path = get_company_dir() / "state/efficiency_data.json"
    if not path.exists():
        return {}
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}


def load_work_queue() -> dict:
    """Load work queue."""
    _ensure_imports()
    return work_allocator.load_queue()


def get_employee_task_history(employee_id: str, days: int = 30) -> list[dict]:
    """Get recent tasks completed by an employee."""
    queue = load_work_queue()
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)

    tasks = []
    for task in queue.get("completed", []):
        if task.get("executed_by") != employee_id:
            continue

        completed_at = task.get("completed_at")
        if completed_at:
            try:
                dt = datetime.fromisoformat(completed_at.replace("Z", "+00:00"))
                if dt >= cutoff:
                    tasks.append(task)
            except (ValueError, TypeError):
                pass

    return tasks


def get_employee_memory(employee_id: str) -> str:
    """Load employee's memory file content."""
    employee = get_employee(employee_id)
    if not employee:
        return ""

    memory_path = employee.get("memoryPath")
    if not memory_path:
        return ""

    # Resolve relative to project root
    project_root = get_company_dir().parent
    full_path = project_root / memory_path

    if not full_path.exists():
        return ""

    try:
        return full_path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _title_pattern_words(title: str) -> list[str]:
    """Discriminating tokens for pattern-frequency analysis.

    Delegates to learned_antipatterns.signature(), which already strips
    stopwords (e.g. "for", "test", "add") that caused analyze_task_patterns
    to mistake shared title phrasing (e.g. "... for: X") for a repeated,
    automatable task class. Falls back to naive splitting if the import
    fails, so this never hard-fails the caller.
    """
    try:
        try:
            from . import learned_antipatterns as la  # type: ignore[attr-defined]
        except ImportError:
            import learned_antipatterns as la  # type: ignore[no-redef]
        return la.signature(title)
    except Exception:
        return [w for w in title.lower().split() if len(w) > 3]


def analyze_task_patterns(tasks: list[dict]) -> dict:
    """Analyze patterns in employee's task history."""
    if not tasks:
        return {"total": 0, "patterns": []}

    # Count task types and titles
    title_words = {}
    complexity_dist = {}
    capabilities_used = {}

    for task in tasks:
        # Extract title patterns
        title = task.get("title", "")
        for word in _title_pattern_words(title):
            if len(word) > 3:  # Skip short words
                title_words[word] = title_words.get(word, 0) + 1

        # Complexity distribution
        complexity = task.get("estimated_complexity", "standard")
        complexity_dist[complexity] = complexity_dist.get(complexity, 0) + 1

        # Capabilities
        for cap in task.get("required_capabilities", []):
            capabilities_used[cap] = capabilities_used.get(cap, 0) + 1

    # Find repeated patterns (words appearing 3+ times)
    patterns = [
        {"word": word, "count": count}
        for word, count in sorted(title_words.items(), key=lambda x: -x[1])
        if count >= 3
    ][:5]

    return {
        "total": len(tasks),
        "patterns": patterns,
        "complexity_distribution": complexity_dist,
        "capabilities_used": capabilities_used,
    }


def analyze_bottlenecks(employee_id: str) -> list[dict]:
    """Analyze bottlenecks from retry history and failures."""
    queue = load_work_queue()
    outcomes = load_learning_outcomes()

    bottlenecks = []

    # Check for tasks with retries
    for task in queue.get("completed", []):
        if task.get("executed_by") != employee_id:
            continue

        retry_count = task.get("retry_count", 0)
        if retry_count >= 2:
            bottlenecks.append(
                {
                    "type": "high_retry",
                    "task_id": task.get("task_id"),
                    "title": task.get("title"),
                    "retry_count": retry_count,
                    "severity": "medium" if retry_count < 3 else "high",
                }
            )

    # Check learning outcomes for failures
    for outcome in outcomes:
        if outcome.get("employee_id") != employee_id:
            continue
        if not outcome.get("success", True):
            bottlenecks.append(
                {
                    "type": "task_failure",
                    "task_id": outcome.get("task_id"),
                    "complexity": outcome.get("complexity"),
                    "severity": "high",
                }
            )

    return bottlenecks


def analyze_capability_gaps(employee_id: str) -> list[dict]:
    """Find capabilities the employee is often asked for but doesn't have."""
    efficiency_data = load_efficiency_data()
    employee = get_employee(employee_id)

    if not employee:
        return []

    current_caps = set(employee.get("capabilities", []))
    gaps = []

    # Check capability gap history
    gap_history = efficiency_data.get("capability_gaps", {}).get("gap_history", [])

    # Count gaps where this employee was the fallback
    gap_counts = {}
    for gap in gap_history:
        if gap.get("fallback_employee") == employee_id:
            for missing in gap.get("missing", []):
                if missing not in current_caps:
                    gap_counts[missing] = gap_counts.get(missing, 0) + 1

    # Capabilities requested 2+ times
    for cap, count in sorted(gap_counts.items(), key=lambda x: -x[1]):
        if count >= 2:
            gaps.append(
                {
                    "capability": cap,
                    "request_count": count,
                    "currently_has": False,
                }
            )

    return gaps[:5]  # Top 5 gaps


def find_collaboration_opportunities(employee_id: str) -> list[dict]:
    """Find employees with overlapping work for collaboration."""
    load_work_queue()
    org = load_org()

    employee = get_employee(employee_id)
    if not employee:
        return []

    my_caps = set(employee.get("capabilities", []))
    my_tasks = get_employee_task_history(employee_id, days=14)
    my_task_caps = set()

    for task in my_tasks:
        my_task_caps.update(task.get("required_capabilities", []))

    opportunities = []

    for emp in org.get("employees", []):
        if emp.get("id") == employee_id:
            continue

        their_caps = set(emp.get("capabilities", []))
        overlap = my_caps & their_caps

        if len(overlap) >= 2:
            # Get their recent tasks
            their_tasks = get_employee_task_history(emp.get("id"), days=14)

            if len(my_tasks) > 0 and len(their_tasks) > 0:
                opportunities.append(
                    {
                        "employee_id": emp.get("id"),
                        "employee_name": emp.get("name"),
                        "shared_capabilities": list(overlap),
                        "overlap_count": len(overlap),
                        "their_recent_task_count": len(their_tasks),
                    }
                )

    # Sort by overlap
    return sorted(opportunities, key=lambda x: -x["overlap_count"])[:3]


def generate_process_improvement_idea(
    employee_id: str,
    patterns: dict,
    task_history: list[dict],
) -> Idea | None:
    """Generate process improvement idea from task patterns."""
    if patterns["total"] < 5:
        return None  # Not enough data

    repeated_patterns = patterns.get("patterns", [])
    if not repeated_patterns:
        return None

    top_pattern = repeated_patterns[0]
    if top_pattern["count"] < 3:
        return None

    employee = get_employee(employee_id)
    employee_name = employee.get("name", employee_id) if employee else employee_id

    # Find example tasks
    example_tasks = [
        t for t in task_history if top_pattern["word"] in t.get("title", "").lower()
    ][:3]

    return Idea(
        idea_id=generate_idea_id(employee_id, "process"),
        employee_id=employee_id,
        idea_type=IdeationType.PROCESS_IMPROVEMENT,
        title=f"Automate repeated '{top_pattern['word']}' tasks",
        description=(
            f"I've completed {top_pattern['count']} tasks related to '{top_pattern['word']}' "
            f"in the past 30 days. This pattern suggests we could benefit from automation or "
            f"a standardized workflow to reduce manual effort."
        ),
        rationale=(
            f"As {employee_name}, I've noticed this repetitive work pattern. "
            f"Creating a reusable template, script, or workflow would save time "
            f"and ensure consistency across similar tasks."
        ),
        evidence=[
            {"task_id": t.get("task_id"), "title": t.get("title")}
            for t in example_tasks
        ],
        estimated_value=min(0.9, 0.3 + (top_pattern["count"] * 0.1)),
        estimated_effort="standard",
        created_at=datetime.now(timezone.utc).isoformat(),
        related_tasks=[t.get("task_id") for t in example_tasks],
        tags=["automation", "efficiency", top_pattern["word"]],
    )


def generate_bottleneck_idea(
    employee_id: str,
    bottlenecks: list[dict],
) -> Idea | None:
    """Generate idea from observed bottlenecks."""
    if not bottlenecks:
        return None

    # Group by type
    high_retry = [b for b in bottlenecks if b.get("type") == "high_retry"]
    failures = [b for b in bottlenecks if b.get("type") == "task_failure"]

    employee = get_employee(employee_id)
    employee_name = employee.get("name", employee_id) if employee else employee_id

    if high_retry:
        # Focus on retry bottleneck
        total_retries = sum(b.get("retry_count", 0) for b in high_retry)

        return Idea(
            idea_id=generate_idea_id(employee_id, "bottleneck"),
            employee_id=employee_id,
            idea_type=IdeationType.BOTTLENECK_OBSERVATION,
            title=f"Reduce task retry rate ({len(high_retry)} tasks with multiple retries)",
            description=(
                f"I've observed {len(high_retry)} tasks that required {total_retries} total "
                f"retries to complete. This suggests there may be unclear requirements, "
                f"missing context, or environmental issues causing initial failures."
            ),
            rationale=(
                f"As {employee_name}, these retries cost time and indicate friction. "
                f"Investigating the root cause could prevent future retry cycles."
            ),
            evidence=[
                {
                    "task_id": b.get("task_id"),
                    "title": b.get("title"),
                    "retry_count": b.get("retry_count"),
                }
                for b in high_retry[:5]
            ],
            estimated_value=0.6,
            estimated_effort="standard",
            created_at=datetime.now(timezone.utc).isoformat(),
            related_tasks=[b.get("task_id") for b in high_retry],
            tags=["bottleneck", "reliability", "retry-reduction"],
        )

    if failures:
        return Idea(
            idea_id=generate_idea_id(employee_id, "bottleneck"),
            employee_id=employee_id,
            idea_type=IdeationType.BOTTLENECK_OBSERVATION,
            title=f"Investigate task failure pattern ({len(failures)} failures)",
            description=(
                f"I've experienced {len(failures)} task failures recently. "
                f"Understanding the common causes could improve our success rate."
            ),
            rationale=(
                f"As {employee_name}, I want to understand why these tasks failed "
                f"so I can prevent similar failures in the future."
            ),
            evidence=[
                {"task_id": f.get("task_id"), "complexity": f.get("complexity")}
                for f in failures[:5]
            ],
            estimated_value=0.5,
            estimated_effort="trivial",
            created_at=datetime.now(timezone.utc).isoformat(),
            related_tasks=[f.get("task_id") for f in failures],
            tags=["bottleneck", "failure-analysis"],
        )

    return None


def generate_capability_expansion_idea(
    employee_id: str,
    gaps: list[dict],
) -> Idea | None:
    """Generate idea for capability self-expansion."""
    if not gaps:
        return None

    top_gap = gaps[0]
    if top_gap["request_count"] < 2:
        return None

    employee = get_employee(employee_id)
    employee_name = employee.get("name", employee_id) if employee else employee_id

    return Idea(
        idea_id=generate_idea_id(employee_id, "capability"),
        employee_id=employee_id,
        idea_type=IdeationType.CAPABILITY_EXPANSION,
        title=f"Add '{top_gap['capability']}' to my capabilities",
        description=(
            f"I've been assigned as fallback for {top_gap['request_count']} tasks "
            f"requiring '{top_gap['capability']}' which I don't officially have. "
            f"I've handled these tasks successfully and could formally add this capability."
        ),
        rationale=(
            f"As {employee_name}, I've demonstrated ability in this area through "
            f"successful task completion. Formalizing this capability would improve "
            f"task routing accuracy and reduce fallback assignments."
        ),
        evidence=[
            {
                "capability": top_gap["capability"],
                "times_handled_as_fallback": top_gap["request_count"],
            }
        ],
        estimated_value=0.7,
        estimated_effort="trivial",
        created_at=datetime.now(timezone.utc).isoformat(),
        tags=["capability", "upskill", top_gap["capability"]],
    )


def generate_collaboration_idea(
    employee_id: str,
    opportunities: list[dict],
) -> Idea | None:
    """Generate collaboration proposal."""
    if not opportunities:
        return None

    top_opp = opportunities[0]
    if top_opp["overlap_count"] < 2:
        return None

    employee = get_employee(employee_id)
    employee_name = employee.get("name", employee_id) if employee else employee_id

    return Idea(
        idea_id=generate_idea_id(employee_id, "collab"),
        employee_id=employee_id,
        idea_type=IdeationType.COLLABORATION_PROPOSAL,
        title=f"Sync with {top_opp['employee_name']} on shared capabilities",
        description=(
            f"I share {top_opp['overlap_count']} capabilities with {top_opp['employee_name']}: "
            f"{', '.join(top_opp['shared_capabilities'][:3])}. "
            f"We've both been actively working in these areas recently."
        ),
        rationale=(
            f"As {employee_name}, I think syncing with {top_opp['employee_name']} could "
            f"help us share learnings, avoid duplicate work, and potentially pair on "
            f"complex tasks in our shared domains."
        ),
        evidence=[
            {
                "collaborator": top_opp["employee_id"],
                "shared_capabilities": top_opp["shared_capabilities"],
                "their_recent_tasks": top_opp["their_recent_task_count"],
            }
        ],
        estimated_value=0.5,
        estimated_effort="trivial",
        created_at=datetime.now(timezone.utc).isoformat(),
        related_employees=[top_opp["employee_id"]],
        tags=["collaboration", "knowledge-sharing"],
    )


def generate_strategic_observation_idea(
    employee_id: str,
    task_history: list[dict],
    patterns: dict,
) -> Idea | None:
    """Generate strategic observation from work patterns."""
    if patterns["total"] < 10:
        return None

    employee = get_employee(employee_id)
    employee_name = employee.get("name", employee_id) if employee else employee_id

    # Look at complexity distribution
    complexity_dist = patterns.get("complexity_distribution", {})
    total = sum(complexity_dist.values())

    if total < 10:
        return None

    # Check for complexity imbalance
    complex_ratio = (
        complexity_dist.get("complex", 0) + complexity_dist.get("epic", 0)
    ) / total
    trivial_ratio = complexity_dist.get("trivial", 0) / total

    if complex_ratio > 0.3:
        return Idea(
            idea_id=generate_idea_id(employee_id, "strategic"),
            employee_id=employee_id,
            idea_type=IdeationType.STRATEGIC_OBSERVATION,
            title="High complexity workload may indicate need for decomposition",
            description=(
                f"{int(complex_ratio * 100)}% of my recent tasks were complex or epic. "
                f"This high ratio suggests we may benefit from better task decomposition "
                f"at the planning stage to enable more parallel execution."
            ),
            rationale=(
                f"As {employee_name}, I'm observing that many tasks arrive already complex. "
                f"Breaking them down earlier would improve throughput and reduce risk."
            ),
            evidence=[
                {"complexity_distribution": complexity_dist, "total_tasks": total}
            ],
            estimated_value=0.6,
            estimated_effort="standard",
            created_at=datetime.now(timezone.utc).isoformat(),
            tags=["strategic", "planning", "decomposition"],
        )

    if trivial_ratio > 0.5:
        return Idea(
            idea_id=generate_idea_id(employee_id, "strategic"),
            employee_id=employee_id,
            idea_type=IdeationType.STRATEGIC_OBSERVATION,
            title="High trivial task ratio may indicate automation opportunity",
            description=(
                f"{int(trivial_ratio * 100)}% of my recent tasks were trivial. "
                f"This suggests many tasks could potentially be automated or batched."
            ),
            rationale=(
                f"As {employee_name}, spending time on many trivial tasks suggests "
                f"we could free up capacity by automating routine work."
            ),
            evidence=[
                {"complexity_distribution": complexity_dist, "total_tasks": total}
            ],
            estimated_value=0.5,
            estimated_effort="standard",
            created_at=datetime.now(timezone.utc).isoformat(),
            tags=["strategic", "automation", "efficiency"],
        )

    return None


def run_ideation_for_employee(
    employee_id: str,
    max_ideas: int = 3,
    dry_run: bool = False,
) -> list[Idea]:
    """Run creative ideation for a single employee.

    Primary path: goal decomposition from active vision.md goals — each idea
    advances a specific goal referenced by ID and target metric, so the
    company ideates on its product, not on itself.

    Fallback: task-history template analysis when no valid product context
    exists (vision.md absent or has no parseable goal table).

    Returns list of ideas generated (not necessarily saved).
    """
    employee = get_employee(employee_id)
    if not employee:
        return []

    product_ctx = load_product_context()

    if product_ctx.is_valid:
        # Primary: goal-decomposition — all employees contribute to shared product goals
        ideas = generate_goal_decomposition_ideas(
            employee_id, employee, product_ctx, max_ideas
        )
        ideas = [
            idea
            for idea in ideas
            if not is_duplicate_idea(idea.title, idea.idea_type.value)[0]
        ]
    else:
        # Fallback: task-history template analysis (no valid vision.md)
        efficiency = employee.get("efficiency", {})
        if efficiency.get("tasks_completed", 0) < 3:
            # Safe default: no product context + no task history → no ideas
            ideas = []
        else:
            task_history = get_employee_task_history(employee_id, days=30)
            patterns = analyze_task_patterns(task_history)
            bottlenecks = analyze_bottlenecks(employee_id)
            capability_gaps = analyze_capability_gaps(employee_id)
            collaboration_opps = find_collaboration_opportunities(employee_id)

            ideas = []

            process_idea = generate_process_improvement_idea(
                employee_id, patterns, task_history
            )
            if process_idea:
                ideas.append(process_idea)

            bottleneck_idea = generate_bottleneck_idea(employee_id, bottlenecks)
            if bottleneck_idea:
                ideas.append(bottleneck_idea)

            capability_idea = generate_capability_expansion_idea(
                employee_id, capability_gaps
            )
            if capability_idea:
                ideas.append(capability_idea)

            collab_idea = generate_collaboration_idea(employee_id, collaboration_opps)
            if collab_idea:
                ideas.append(collab_idea)

            strategic_idea = generate_strategic_observation_idea(
                employee_id, task_history, patterns
            )
            if strategic_idea:
                ideas.append(strategic_idea)

            ideas.sort(key=lambda x: -x.estimated_value)
            ideas = ideas[:max_ideas]

            ideas = [
                idea
                for idea in ideas
                if not is_duplicate_idea(idea.title, idea.idea_type.value)[0]
            ]

    # Save and route for approval if not dry run
    if not dry_run and ideas:
        data = load_ideas()
        existing_ids = {i.get("idea_id") for i in data.get("ideas", [])}
        config = load_ideation_config()

        for idea in ideas:
            if idea.idea_id not in existing_ids:
                idea_dict = idea.to_dict()
                data["ideas"].append(idea_dict)

        save_ideas(data)

        for idea in ideas:
            route_idea_for_approval(idea.to_dict(), config)

    return ideas


def _load_ideation_rotation() -> dict:
    """Load ideation rotation state, returning default if missing."""
    path = get_company_dir() / "state" / "ideation_rotation.json"
    if path.exists():
        try:
            data = json.loads(path.read_text())
            if not isinstance(data.get("recently_targeted"), list):
                return {"recently_targeted": [], "last_updated": ""}
            return data
        except (json.JSONDecodeError, OSError):
            pass
    return {"recently_targeted": [], "last_updated": ""}


def _save_ideation_rotation(state: dict) -> None:
    """Save ideation rotation state with atomic write."""
    import os
    import tempfile

    path = get_company_dir() / "state" / "ideation_rotation.json"
    path.parent.mkdir(parents=True, exist_ok=True)

    state["last_updated"] = datetime.now(timezone.utc).isoformat()

    fd, tmp_path = tempfile.mkstemp(dir=path.parent, suffix=".json")
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(state, f, indent=2)
        os.replace(tmp_path, path)
    except Exception:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise


def _recover_stranded_proposed_ideas(cycle_interval_minutes: int = 30) -> int:
    """Route ideas stuck in 'proposed' from a prior crashed cycle.

    An idea stays 'proposed' when a crash occurred after save_ideas() but before
    route_idea_for_approval() completed.  Cross-run dedup blocks regenerating them,
    so they must be re-routed here.  Returns the number of ideas recovered.
    """
    data = load_ideas()
    cutoff = datetime.now(timezone.utc) - timedelta(minutes=cycle_interval_minutes)
    config = load_ideation_config()
    recovered = 0
    for idea in data.get("ideas", []):
        if idea.get("status") != "proposed":
            continue
        try:
            created_at = datetime.fromisoformat(
                idea["created_at"].replace("Z", "+00:00")
            )
        except (KeyError, ValueError):
            continue
        if created_at < cutoff:
            route_idea_for_approval(idea, config)
            recovered += 1
    return recovered


def run_ideation_cycle(
    max_employees: int = 3,
    max_ideas_per_employee: int = 2,
    dry_run: bool = False,
    target_zero_activity: bool = False,
) -> dict:
    """
    Run ideation cycle for multiple employees.

    When target_zero_activity is True, targets under-represented employees
    (tasks_completed < 3) with domain-specific prompts instead of the
    usual high-activity employees.

    Returns summary of ideas generated.
    """
    if not dry_run:
        _recover_stranded_proposed_ideas()

    org = load_org()
    employees = org.get("employees", [])

    if not employees:
        print(
            "warning: no employees configured in org.json; ideation cycle skipped."
            " Run /company-hire to add employees first.",
            file=sys.stderr,
        )
        return {
            "employees_processed": [],
            "ideas_generated": [],
            "total_ideas": 0,
            "auto_approved": 0,
            "pending_manager": 0,
            "pending_executive": 0,
            "dry_run": dry_run,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

    if target_zero_activity:
        # Target under-represented employees with < 3 completed tasks
        zero_activity = []
        for emp in employees:
            efficiency = emp.get("efficiency", {})
            tasks_completed = efficiency.get("tasks_completed", 0)
            if tasks_completed < 3:
                zero_activity.append((emp, tasks_completed))
        # Sort: partial activity first, then alphabetical for determinism
        zero_activity.sort(key=lambda x: (-x[1], x[0].get("id", "")))

        # Apply rotation: filter out recently targeted employees
        rotation = _load_ideation_rotation()
        recently_targeted = set(rotation.get("recently_targeted", []))
        all_zero_ids = {e[0].get("id") for e in zero_activity}

        # If all zero-activity employees have been recently targeted, reset
        if all_zero_ids and all_zero_ids.issubset(recently_targeted):
            recently_targeted = set()
            rotation["recently_targeted"] = []

        # Filter out recently targeted
        filtered = [
            (emp, tc)
            for emp, tc in zero_activity
            if emp.get("id") not in recently_targeted
        ]
        selected = [e[0] for e in filtered[:max_employees]]

        # Update rotation state with newly targeted employee IDs
        newly_targeted = [emp.get("id") for emp in selected if emp.get("id")]
        rotation["recently_targeted"] = list(recently_targeted) + newly_targeted
        _save_ideation_rotation(rotation)
    else:
        # Process ALL employees: high-activity ones use task-history ideation,
        # low-activity ones get product-grounded ideation from the shared goal set.
        employees_with_count = []
        for emp in employees:
            efficiency = emp.get("efficiency", {})
            tasks_completed = efficiency.get("tasks_completed", 0)
            employees_with_count.append((emp, tasks_completed))
        # Sort: high-activity first, then alphabetical for determinism
        employees_with_count.sort(key=lambda x: (-x[1], x[0].get("id", "")))
        selected = [e[0] for e in employees_with_count[:max_employees]]

    results = {
        "employees_processed": [],
        "ideas_generated": [],
        "total_ideas": 0,
        "auto_approved": 0,
        "pending_manager": 0,
        "pending_executive": 0,
        "dry_run": dry_run,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

    for emp in selected:
        emp_id = emp.get("id")
        ideas = run_ideation_for_employee(
            emp_id,
            max_ideas=max_ideas_per_employee,
            dry_run=dry_run,
        )

        results["employees_processed"].append(emp_id)
        for idea in ideas:
            # Get approval level for tracking
            level = get_approval_level(idea)

            results["ideas_generated"].append(
                {
                    "idea_id": idea.idea_id,
                    "employee_id": idea.employee_id,
                    "type": idea.idea_type.value,
                    "title": idea.title,
                    "value": idea.estimated_value,
                    "approval_level": level.value,
                }
            )

            # Track by approval level
            if level == ApprovalLevel.AUTO:
                results["auto_approved"] += 1
            elif level == ApprovalLevel.MANAGER:
                results["pending_manager"] += 1
            else:
                results["pending_executive"] += 1

        results["total_ideas"] += len(ideas)

    # Fire one notification if any ideas entered pending_approval this batch
    pending_count = results["pending_manager"] + results["pending_executive"]
    if pending_count > 0 and not dry_run:
        queued_ids = [
            i["idea_id"]
            for i in results["ideas_generated"]
            if i.get("approval_level") in ("manager", "executive")
        ]
        fire_pending_approvals_notification(pending_count, queued_ids)

    return results


def get_ideation_stats() -> dict:
    """Get statistics about employee ideation."""
    data = load_ideas()
    ideas = data.get("ideas", [])

    now = datetime.now(timezone.utc)
    day_ago = now - timedelta(days=1)
    week_ago = now - timedelta(days=7)

    stats = {
        "total_ideas": len(ideas),
        "ideas_last_24h": 0,
        "ideas_last_week": 0,
        "by_type": {},
        "by_employee": {},
        "by_status": {},
        "avg_value": 0.0,
    }

    total_value = 0.0

    for idea in ideas:
        # Count by time
        created_at = idea.get("created_at", "")
        try:
            dt = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
            if dt >= day_ago:
                stats["ideas_last_24h"] += 1
            if dt >= week_ago:
                stats["ideas_last_week"] += 1
        except (ValueError, TypeError):
            pass

        # Count by type
        idea_type = idea.get("idea_type", "unknown")
        stats["by_type"][idea_type] = stats["by_type"].get(idea_type, 0) + 1

        # Count by employee
        emp_id = idea.get("employee_id", "unknown")
        stats["by_employee"][emp_id] = stats["by_employee"].get(emp_id, 0) + 1

        # Count by status
        status = idea.get("status", "proposed")
        stats["by_status"][status] = stats["by_status"].get(status, 0) + 1

        # Sum value
        total_value += idea.get("estimated_value", 0.0)

    if ideas:
        stats["avg_value"] = round(total_value / len(ideas), 2)

    return stats


def list_recent_ideas(days: int = 7, status: str | None = None) -> list[dict]:
    """List recent ideas."""
    data = load_ideas()
    ideas = data.get("ideas", [])

    cutoff = datetime.now(timezone.utc) - timedelta(days=days)

    results = []
    for idea in ideas:
        # Filter by time
        created_at = idea.get("created_at", "")
        try:
            dt = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
            if dt < cutoff:
                continue
        except (ValueError, TypeError):
            continue

        # Filter by status
        if status and idea.get("status") != status:
            continue

        results.append(idea)

    # Sort by created_at desc
    results.sort(key=lambda x: x.get("created_at", ""), reverse=True)

    return results


class ApprovalLevel(Enum):
    """Approval levels for ideas - mirrors real company hierarchy."""

    AUTO = "auto"  # Low-value ideas, auto-approve
    MANAGER = "manager"  # Medium ideas, manager review
    EXECUTIVE = "executive"  # High-value/strategic, C-level approval


# Thresholds for routing (defaults — overridden by forge-config.json employeeIdeation)
APPROVAL_THRESHOLDS = {
    "auto_max_value": 0.7,  # Ideas <= 0.7 value can auto-approve (WS-054-001)
    "manager_max_value": 0.85,  # Ideas <= 0.85 go to manager, above goes to executive
    "auto_max_effort": ["trivial", "standard"],  # Only auto-approve low-effort ideas
    "auto_daily_cap": 5,  # Max auto-approvals per day
}

# Strategic idea types always go to executive
EXECUTIVE_IDEA_TYPES = {
    IdeationType.STRATEGIC_OBSERVATION,
    IdeationType.ARCHITECTURE_INSIGHT,
}


def get_approval_level(idea: Idea | dict, config: dict | None = None) -> ApprovalLevel:
    """
    Determine approval level for an idea based on value, effort, and type.

    Routing logic (WS-054-001 — config-driven):
    - Strategic/architecture ideas -> Executive (forge-ceo, forge-cto)
    - Value <= auto_max_value AND effort in auto_max_effort -> Auto-approve
    - Value <= manager_max_value -> Manager review
    - Above manager_max_value -> Executive
    """
    if config is None:
        config = load_ideation_config()

    if isinstance(idea, dict):
        idea_type = idea.get("idea_type", "")
        if isinstance(idea_type, str):
            try:
                idea_type = IdeationType(idea_type)
            except ValueError:
                idea_type = None
        value = idea.get("estimated_value", 0.5)
        effort = idea.get("estimated_effort", "standard")
    else:
        idea_type = idea.idea_type
        value = idea.estimated_value
        effort = getattr(idea, "estimated_effort", "standard")

    # Strategic ideas always need executive approval
    if idea_type in EXECUTIVE_IDEA_TYPES:
        return ApprovalLevel.EXECUTIVE

    # Config-driven thresholds (fall back to module defaults)
    auto_max_value = config.get(
        "autoApproveMaxValue", APPROVAL_THRESHOLDS["auto_max_value"]
    )
    manager_max_value = config.get(
        "managerApproveMaxValue", APPROVAL_THRESHOLDS["manager_max_value"]
    )
    auto_max_effort = config.get(
        "autoApproveMaxEffort", APPROVAL_THRESHOLDS["auto_max_effort"]
    )

    # Route by value AND effort
    if value <= auto_max_value and effort in auto_max_effort:
        return ApprovalLevel.AUTO
    elif value <= manager_max_value:
        return ApprovalLevel.MANAGER
    else:
        return ApprovalLevel.EXECUTIVE


def _auto_approvals_today() -> int:
    """Count how many ideas were auto-approved today (for daily cap)."""
    data = load_ideas()
    today = datetime.now(timezone.utc).date().isoformat()
    count = 0
    for idea in data.get("ideas", []):
        if idea.get("approved_by") == "auto" and idea.get("approved_at", "").startswith(
            today
        ):
            count += 1
    return count


def route_idea_for_approval(idea: dict, config: dict | None = None) -> dict:
    """
    Route an idea to the appropriate approval authority.

    Returns dict with routing result:
    - auto_approved: True if auto-approved
    - approval_level: The level required
    - approvers: List of approver IDs (for manager/executive)
    - queued: True if added to pending approvals
    """
    if config is None:
        config = load_ideation_config()

    level = get_approval_level(idea, config)
    result = {
        "idea_id": idea.get("idea_id"),
        "approval_level": level.value,
        "auto_approved": False,
        "approvers": [],
        "queued": False,
    }

    if level == ApprovalLevel.AUTO:
        # Check if auto-approval is enabled and within daily cap
        if config.get("autoApproveEnabled", True):
            daily_cap = config.get(
                "autoApproveDailyCap",
                APPROVAL_THRESHOLDS.get("auto_daily_cap", 5),
            )
            if _auto_approvals_today() < daily_cap:
                approve_result = approve_idea(idea.get("idea_id"), approved_by="auto")
                result["auto_approved"] = approve_result.get("success", False)
                return result
            else:
                # Daily cap reached, fall through to manager review
                level = ApprovalLevel.MANAGER
        else:
            # Fall through to manager review
            level = ApprovalLevel.MANAGER

    if level == ApprovalLevel.MANAGER:
        # Queue for manager review
        result["approvers"] = get_managers_for_employee(idea.get("employee_id"))
        if not result["approvers"]:
            # No manager found, escalate to executive
            level = ApprovalLevel.EXECUTIVE
        else:
            queue_idea_for_approval(idea, level, result["approvers"])
            result["queued"] = True
            return result

    if level == ApprovalLevel.EXECUTIVE:
        # Queue for C-level review
        result["approvers"] = get_executives()
        queue_idea_for_approval(idea, level, result["approvers"])
        result["queued"] = True

    return result


def get_managers_for_employee(employee_id: str) -> list[str]:
    """Get manager(s) for an employee."""
    org = load_org()

    # Find employee's department
    employee = None
    for emp in org.get("employees", []):
        if emp.get("id") == employee_id:
            employee = emp
            break

    if not employee:
        return []

    department = employee.get("department", "")

    # Find department head or team lead
    managers = []
    for emp in org.get("employees", []):
        if emp.get("id") == employee_id:
            continue

        # Check if this is a manager-level employee
        emp.get("type", "")
        emp_caps = set(emp.get("capabilities", []))

        # Manager indicators
        is_lead = (
            "lead" in emp.get("id", "").lower() or "lead" in emp.get("name", "").lower()
        )
        has_management_cap = "management" in emp_caps or "leadership" in emp_caps
        same_dept = emp.get("department") == department

        if (is_lead or has_management_cap) and same_dept:
            managers.append(emp.get("id"))

    return managers[:2]  # Max 2 managers


def get_executives() -> list[str]:
    """Get C-level executives for approval."""
    org = load_org()

    executives = []
    for emp in org.get("employees", []):
        emp_id = emp.get("id", "").lower()
        emp_name = emp.get("name", "").lower()

        # C-level indicators
        is_ceo = "ceo" in emp_id or "ceo" in emp_name
        is_cto = "cto" in emp_id or "cto" in emp_name
        is_cfo = "cfo" in emp_id or "cfo" in emp_name

        if is_ceo or is_cto or is_cfo:
            executives.append(emp.get("id"))

    return executives if executives else ["forge-ceo", "forge-cto"]


def queue_idea_for_approval(
    idea: dict,
    level: ApprovalLevel,
    approvers: list[str],
) -> None:
    """Add idea to pending approvals queue."""
    pending_path = get_company_dir() / "state/pending_approvals.json"

    try:
        if pending_path.exists():
            with open(pending_path) as f:
                pending = json.load(f)
        else:
            pending = {"proposals": []}
    except (json.JSONDecodeError, OSError):
        pending = {"proposals": []}

    # Create proposal entry for the idea
    proposal = {
        "proposal_id": idea.get("idea_id"),
        "proposal_type": "employee_idea",
        "title": idea.get("title", "Employee Idea"),
        "description": idea.get("description", ""),
        "rationale": idea.get("rationale", ""),
        "estimated_effort_minutes": 30
        if idea.get("estimated_effort") == "standard"
        else 15,
        "estimated_value": idea.get("estimated_value", 0.5),
        "roi_score": idea.get("estimated_value", 0.5) * 2,  # Simple ROI
        "approval_tier": level.value,
        "approval_required": approvers,
        "source_data": {
            "idea_id": idea.get("idea_id"),
            "employee_id": idea.get("employee_id"),
            "idea_type": idea.get("idea_type"),
            "evidence": idea.get("evidence", []),
        },
        "created_at": datetime.now(timezone.utc).isoformat(),
        "status": "pending",
        "priority": 3,
    }

    # Avoid duplicates
    existing_ids = {p.get("proposal_id") for p in pending.get("proposals", [])}
    if proposal["proposal_id"] not in existing_ids:
        pending["proposals"].append(proposal)

        # Atomic write
        import os
        import tempfile

        pending_path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp_path = tempfile.mkstemp(dir=pending_path.parent, suffix=".json")
        try:
            with os.fdopen(fd, "w") as f:
                json.dump(pending, f, indent=2)
            os.replace(tmp_path, pending_path)
        except Exception:
            if os.path.exists(tmp_path):
                os.unlink(tmp_path)
            raise

    # Update idea status
    data = load_ideas()
    for stored_idea in data.get("ideas", []):
        if stored_idea.get("idea_id") == idea.get("idea_id"):
            stored_idea["status"] = "pending_approval"
            stored_idea["approval_level"] = level.value
            stored_idea["pending_approvers"] = approvers
            break
    save_ideas(data)


def load_ideation_config() -> dict:
    """Load ideation configuration from forge-config.json."""
    config_path = get_company_dir().parent / "forge-config.json"

    if not config_path.exists():
        return {
            "autoApproveEnabled": True,
            "autoApproveMaxValue": 0.7,
            "managerApproveMaxValue": 0.85,
            "autoApproveMaxEffort": ["trivial", "standard"],
            "autoApproveDailyCap": 5,
            "managerApprovalEnabled": True,
            "executiveApprovalEnabled": True,
        }

    try:
        with open(config_path) as f:
            config = json.load(f)
            return config.get("employeeIdeation", {})
    except (json.JSONDecodeError, OSError):
        return {}


def approve_idea(idea_id: str, approved_by: str = "human") -> dict:
    """Approve an idea and optionally convert to task."""
    data = load_ideas()

    for idea in data.get("ideas", []):
        if idea.get("idea_id") == idea_id:
            idea["status"] = "approved"
            idea["approved_by"] = approved_by
            idea["approved_at"] = datetime.now(timezone.utc).isoformat()
            save_ideas(data)

            # Remove from pending approvals if present
            _remove_from_pending(idea_id)

            return {"success": True, "idea": idea}

    return {"success": False, "error": f"Idea {idea_id} not found"}


def _remove_from_pending(idea_id: str) -> None:
    """Remove an idea from pending approvals."""
    pending_path = get_company_dir() / "state/pending_approvals.json"

    if not pending_path.exists():
        return

    try:
        with open(pending_path) as f:
            pending = json.load(f)

        original_count = len(pending.get("proposals", []))
        pending["proposals"] = [
            p for p in pending.get("proposals", []) if p.get("proposal_id") != idea_id
        ]

        if len(pending["proposals"]) < original_count:
            import os
            import tempfile

            fd, tmp_path = tempfile.mkstemp(dir=pending_path.parent, suffix=".json")
            try:
                with os.fdopen(fd, "w") as f:
                    json.dump(pending, f, indent=2)
                os.replace(tmp_path, pending_path)
            except Exception:
                if os.path.exists(tmp_path):
                    os.unlink(tmp_path)
    except (json.JSONDecodeError, OSError):
        pass


def reject_idea(idea_id: str, rejected_by: str = "human", reason: str = "") -> dict:
    """Reject an idea."""
    data = load_ideas()

    for idea in data.get("ideas", []):
        if idea.get("idea_id") == idea_id:
            idea["status"] = "rejected"
            idea["rejected_by"] = rejected_by
            idea["rejected_at"] = datetime.now(timezone.utc).isoformat()
            idea["rejection_reason"] = reason
            save_ideas(data)
            return {"success": True, "idea": idea}

    return {"success": False, "error": f"Idea {idea_id} not found"}


def _create_idea_reference_doc(idea: dict) -> str | None:
    """
    Create a reference document for the idea with full context.

    Returns the path to the created document, or None if creation fails.
    """
    import os
    import tempfile

    idea_id = idea.get("idea_id", "unknown")
    ideas_dir = get_company_dir() / "ideas"
    ideas_dir.mkdir(parents=True, exist_ok=True)

    doc_path = ideas_dir / f"{idea_id}.md"

    # Build evidence section
    evidence_lines = []
    for ev in idea.get("evidence", []):
        if isinstance(ev, dict):
            ev_type = ev.get("type", "observation")
            ev_data = ev.get("data", ev.get("description", str(ev)))
            evidence_lines.append(f"- **{ev_type}**: {ev_data}")
        else:
            evidence_lines.append(f"- {ev}")
    evidence_section = (
        "\n".join(evidence_lines)
        if evidence_lines
        else "No specific evidence recorded."
    )

    # Build related tasks section
    related_tasks = idea.get("related_tasks", [])
    tasks_section = (
        "\n".join(f"- `{t}`" for t in related_tasks) if related_tasks else "None"
    )

    # Build related employees section
    related_employees = idea.get("related_employees", [])
    employees_section = (
        "\n".join(f"- {e}" for e in related_employees) if related_employees else "None"
    )

    # Build tags section
    tags = idea.get("tags", [])
    tags_section = ", ".join(f"`{t}`" for t in tags) if tags else "None"

    doc_content = f"""# Idea: {idea.get("title", "Untitled")}

**ID:** {idea_id}
**Type:** {idea.get("idea_type", "unknown")}
**Proposed By:** {idea.get("employee_id", "unknown")}
**Created:** {idea.get("created_at", "unknown")}
**Status:** {idea.get("status", "proposed")}
**Estimated Value:** {idea.get("estimated_value", "N/A")}
**Estimated Effort:** {idea.get("estimated_effort", "standard")}

## Description

{idea.get("description", "No description provided.")}

## Rationale

{idea.get("rationale", "No rationale provided.")}

## Evidence

{evidence_section}

## Related Tasks

{tasks_section}

## Related Employees

{employees_section}

## Tags

{tags_section}

---
*This document was auto-generated from employee ideation. Reference it for full context when implementing.*
"""

    # Atomic write
    try:
        fd, tmp_path = tempfile.mkstemp(dir=ideas_dir, suffix=".md")
        with os.fdopen(fd, "w") as f:
            f.write(doc_content)
        os.replace(tmp_path, doc_path)
        return str(doc_path)
    except Exception:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        return None


def idea_to_task(idea: dict) -> dict:
    """
    Convert an approved idea to a work queue task.

    IMPORTANT: This function preserves full context from the idea:
    - Creates a reference document at .company/ideas/{idea_id}.md
    - Includes evidence summary in description
    - Preserves related_tasks and related_employees
    - Maintains all tags (not truncated)
    """
    _ensure_imports()

    # Map idea type to task priority
    priority_map = {
        "process_improvement": 3,
        "bottleneck_observation": 2,
        "capability_expansion": 4,
        "collaboration_proposal": 4,
        "tool_suggestion": 3,
        "architecture_insight": 3,
        "strategic_observation": 3,
    }

    # Map effort to complexity
    effort_map = {
        "trivial": "trivial",
        "standard": "standard",
        "complex": "complex",
    }

    idea_type = idea.get("idea_type", "process_improvement")
    idea_id = idea.get("idea_id", "")

    # Create reference document with full context
    ref_doc_path = _create_idea_reference_doc(idea)

    # Build rich description with evidence
    description_parts = [idea.get("description", "")]

    # Add rationale
    rationale = idea.get("rationale", "")
    if rationale:
        description_parts.append(f"\n\n**Rationale:** {rationale}")

    # Add evidence summary (critical for implementation context)
    evidence = idea.get("evidence", [])
    if evidence:
        description_parts.append("\n\n**Evidence:**")
        for ev in evidence[:5]:  # Include up to 5 evidence items inline
            if isinstance(ev, dict):
                ev_type = ev.get("type", "observation")
                ev_data = ev.get("data", ev.get("description", str(ev)))
                description_parts.append(f"\n- {ev_type}: {ev_data}")
            else:
                description_parts.append(f"\n- {ev}")
        if len(evidence) > 5:
            description_parts.append(
                f"\n- ... and {len(evidence) - 5} more (see reference doc)"
            )

    # Add related tasks (so implementer knows what to reference)
    related_tasks = idea.get("related_tasks", [])
    if related_tasks:
        description_parts.append(
            f"\n\n**Related Tasks:** {', '.join(related_tasks[:5])}"
        )
        if len(related_tasks) > 5:
            description_parts.append(f" (and {len(related_tasks) - 5} more)")

    # Add related employees (for coordination)
    related_employees = idea.get("related_employees", [])
    if related_employees:
        description_parts.append(
            f"\n\n**Coordinate With:** {', '.join(related_employees)}"
        )

    # Reference the full idea document
    if ref_doc_path:
        description_parts.append(
            f"\n\n**Full Context:** See `.company/ideas/{idea_id}.md`"
        )

    task = {
        "task_id": f"task-{idea_id.replace('idea-', '')}",
        "title": idea.get("title", "Implement employee idea"),
        "description": "".join(description_parts),
        "priority": priority_map.get(idea_type, 3),
        "required_capabilities": idea.get("tags", []),  # Full tags, not truncated
        "estimated_complexity": effort_map.get(
            idea.get("estimated_effort", "standard"), "standard"
        ),
        "source": "employee_ideation",
        "source_idea_id": idea_id,
        "proposed_by": idea.get("employee_id"),
        # NEW: Preserve full context metadata
        "idea_reference_doc": ref_doc_path,
        "related_tasks": related_tasks,
        "related_employees": related_employees,
        "estimated_value": idea.get("estimated_value"),
        "idea_type": idea_type,
    }

    return task


# CLI interface
def main():
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(description="Employee Creative Ideation (P34)")
    subparsers = parser.add_subparsers(dest="command", help="Commands")

    # ideate command
    ideate_parser = subparsers.add_parser("ideate", help="Run ideation for an employee")
    ideate_parser.add_argument("--employee-id", required=True, help="Employee ID")
    ideate_parser.add_argument(
        "--max-ideas", type=int, default=3, help="Max ideas to generate"
    )
    ideate_parser.add_argument(
        "--dry-run", action="store_true", help="Don't save ideas"
    )
    ideate_parser.add_argument("--json", action="store_true", help="Output JSON")

    # cycle command
    cycle_parser = subparsers.add_parser("cycle", help="Run ideation cycle")
    cycle_parser.add_argument(
        "--max-employees", type=int, default=3, help="Max employees"
    )
    cycle_parser.add_argument(
        "--max-ideas", type=int, default=2, help="Max ideas per employee"
    )
    cycle_parser.add_argument("--dry-run", action="store_true", help="Don't save ideas")
    cycle_parser.add_argument(
        "--bootstrap",
        action="store_true",
        help="Target under-represented employees (tasks_completed < 3) with domain-specific prompts",
    )
    cycle_parser.add_argument("--json", action="store_true", help="Output JSON")

    # stats command
    stats_parser = subparsers.add_parser("stats", help="Get ideation stats")
    stats_parser.add_argument("--json", action="store_true", help="Output JSON")

    # list command
    list_parser = subparsers.add_parser("list", help="List recent ideas")
    list_parser.add_argument("--days", type=int, default=7, help="Days to look back")
    list_parser.add_argument("--status", help="Filter by status")
    list_parser.add_argument("--json", action="store_true", help="Output JSON")

    # approve command
    approve_parser = subparsers.add_parser("approve", help="Approve an idea")
    approve_parser.add_argument("idea_id", nargs="?", help="Idea ID (positional)")
    approve_parser.add_argument("--idea-id", dest="idea_id_flag", help="Idea ID (flag)")
    approve_parser.add_argument(
        "--approved-by",
        "--approver",
        dest="approved_by",
        default="human",
        help="Approver",
    )
    approve_parser.add_argument("--json", action="store_true", help="Output JSON")

    # reject command
    reject_parser = subparsers.add_parser("reject", help="Reject an idea")
    reject_parser.add_argument("idea_id", nargs="?", help="Idea ID (positional)")
    reject_parser.add_argument("--idea-id", dest="idea_id_flag", help="Idea ID (flag)")
    reject_parser.add_argument(
        "--rejected-by",
        "--rejecter",
        dest="rejected_by",
        default="human",
        help="Rejecter",
    )
    reject_parser.add_argument("--reason", default="", help="Rejection reason")
    reject_parser.add_argument("--json", action="store_true", help="Output JSON")

    args = parser.parse_args()

    if args.command == "ideate":
        ideas = run_ideation_for_employee(
            args.employee_id,
            max_ideas=args.max_ideas,
            dry_run=args.dry_run,
        )
        result = {
            "employee_id": args.employee_id,
            "ideas": [i.to_dict() for i in ideas],
            "count": len(ideas),
            "dry_run": args.dry_run,
        }
        if args.json:
            print(json.dumps(result, indent=2))
        else:
            print(f"Generated {len(ideas)} ideas for {args.employee_id}:")
            for idea in ideas:
                print(f"  - [{idea.idea_type.value}] {idea.title}")

    elif args.command == "cycle":
        result = run_ideation_cycle(
            max_employees=args.max_employees,
            max_ideas_per_employee=args.max_ideas,
            dry_run=args.dry_run,
            target_zero_activity=args.bootstrap,
        )
        if args.json:
            print(json.dumps(result, indent=2))
        else:
            print("Ideation cycle complete:")
            print(f"  Employees processed: {len(result['employees_processed'])}")
            print(f"  Ideas generated: {result['total_ideas']}")
            for idea in result["ideas_generated"]:
                print(f"    - [{idea['type']}] {idea['title'][:50]}...")

    elif args.command == "stats":
        stats = get_ideation_stats()
        if args.json:
            print(json.dumps(stats, indent=2))
        else:
            print("Ideation Statistics:")
            print(f"  Total ideas: {stats['total_ideas']}")
            print(f"  Last 24h: {stats['ideas_last_24h']}")
            print(f"  Last week: {stats['ideas_last_week']}")
            print(f"  Avg value: {stats['avg_value']}")
            print(f"  By type: {stats['by_type']}")

    elif args.command == "list":
        ideas = list_recent_ideas(days=args.days, status=args.status)
        if args.json:
            print(json.dumps(ideas, indent=2))
        else:
            print(f"Recent ideas ({len(ideas)}):")
            for idea in ideas:
                print(f"  [{idea.get('idea_type')}] {idea.get('title')}")
                print(
                    f"    by {idea.get('employee_id')} | value: {idea.get('estimated_value')}"
                )

    elif args.command == "approve":
        # Support both positional and --idea-id flag
        idea_id = args.idea_id or args.idea_id_flag
        if not idea_id:
            print("Error: idea_id required (positional or --idea-id)")
            sys.exit(2)
        result = approve_idea(idea_id, args.approved_by)
        if args.json:
            print(json.dumps(result, indent=2))
        else:
            if result["success"]:
                print(f"Approved idea {idea_id}")
            else:
                print(f"Error: {result.get('error')}")

    elif args.command == "reject":
        # Support both positional and --idea-id flag
        idea_id = args.idea_id or args.idea_id_flag
        if not idea_id:
            print("Error: idea_id required (positional or --idea-id)")
            sys.exit(2)
        result = reject_idea(idea_id, args.rejected_by, args.reason)
        if args.json:
            print(json.dumps(result, indent=2))
        else:
            if result["success"]:
                print(f"Rejected idea {idea_id}")
            else:
                print(f"Error: {result.get('error')}")

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
